In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/fortune1000.csv")
df

,Rank,Company,Sector,Industry,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
2,3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
3,4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
4,5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400
...,...,...,...,...,...,...,...
995,996,New York Community Bancorp,Financials,Commercial Banks,1902,-47,3448
996,997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
997,997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
998,999,Wendy’s,"Hotels, Resturants & Leisure",Food Services,1896,161,21200
999,1000,Briggs & Stratton,Industrials,Industrial Machinery,1895,46,5480

In [3]:
df=pd.read_csv("/Users/madhanmj/Downloads/python 2 data set/SBA-class-activity-main/fortune1000.csv",index_col="Rank")

In [4]:
df

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400
...,...,...,...,...,...,...
996,New York Community Bancorp,Financials,Commercial Banks,1902,-47,3448
997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
999,Wendy’s,"Hotels, Resturants & Leisure",Food Services,1896,161,21200
1000,Briggs & Stratton,Industrials,Industrial Machinery,1895,46,5480

In [7]:
sectors=df.groupby('Sector')

In [8]:
len(sectors)

21

In [9]:
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [10]:
sectors.first()

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,96114,5176,161400
Apparel,Nike,Apparel,30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,19330,419,27000
Chemicals,Dow Chemical,Chemicals,48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,78756,7036,110000
Industrials,General Electric,Industrial Machinery,140389,-6126,333000
Materials,Alcoa,Metals,22534,-322,60000
Media,Disney,Entertainment,52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,152356,9687,215000
Retailing,Walmart,General Merchandisers,482130,14694,2300000
Technology,Apple,"Computers, Office Equipment",233715,53394,110000
Telecommunications,AT&T,Telecommunications,146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,48681,687,51700

In [21]:
sectors.get_group('Energy')

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
14,Chevron,Energy,Petroleum Refining,131118,4587,61500
30,Phillips 66,Energy,Petroleum Refining,87169,4227,14000
32,Valero Energy,Energy,Petroleum Refining,81824,3990,10103
42,Marathon Petroleum,Energy,Petroleum Refining,64566,2852,45440
...,...,...,...,...,...,...
981,WPX Energy,Energy,"Mining, Crude-Oil Production",1958,-1727,1040
983,Adams Resources & Energy,Energy,Petroleum Refining,1944,-1,809
995,EP Energy,Energy,"Mining, Crude-Oil Production",1908,-3748,665
997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646

In [22]:
sectors['Profits'].sum()

Sector
Aerospace & Defense              28742
Apparel                           8236
Business Services                28227
Chemicals                        22628
Energy                          -73447
Engineering & Construction        5304
Financials                      260209
Food and Drug Stores             16759
Food, Beverages & Tobacco        51417
Health Care                     106114
Hotels, Resturants & Leisure     20697
Household Products               14428
Industrials                      20764
Materials                         4428
Media                            24347
Motor Vehicles & Parts           25898
Retailing                        47830
Technology                      180473
Telecommunications               48637
Transportation                   44169
Wholesalers                       8233
Name: Profits, dtype: int64

In [28]:
sectors.agg({'Profits':})

SyntaxError: expression expected after dictionary key and ':' (2358089705.py, line 1)